# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PUXaKjAdvdJZORt5MYbuAT_4R2Kc2xa4
"""



"""# 🌐 Sai Krishna Sajjanam — Data Analyst Portfolio

Welcome to my personal **Data Analytics Portfolio Website**, built with **React**, **Vite**, **Tailwind CSS**, and **TypeScript**.  
It showcases my experience, projects, certifications, and skills in **SQL, Python, Power BI, Machine Learning**, and more.

---

## 🚀 Live Website
**[View Portfolio →](https://YOUR_USERNAME.github.io/YOUR_REPO/)**  
*(Replace with your actual GitHub Pages URL after deployment)*

---

## 🧩 Tech Stack

| Category | Tools / Frameworks |
|-----------|--------------------|
| Frontend | React (TypeScript), Vite |
| Styling | Tailwind CSS, shadcn/ui |
| Icons | Lucide React |
| Charts / UI | Recharts (for dashboards), Framer Motion |
| Deployment | GitHub Pages (via `gh-pages`) |

---

## 🧰 Features

- 🎨 Clean, modern, and responsive UI  
- 💼 Dynamic sections — *Skills, Experience, Education, Certifications, and Projects*  
- 📊 Power BI & SQL project showcases  
- 📜 Resume download (PDF)  
- 💌 Contact section with email & LinkedIn integration  
- 🌈 Smooth animations and gradient highlights  


"""